### ISSUE TITLE
Do Amplitude based Labels have Forward Looking Bias?

### ISSUE THREAD

**Issue by jkravets1** [tr8dr/tseries-patterns#2]
I really like the amplitude labeler!
Do the labels have forward-looking bias? Is it possible to use them in real time, or are they more for labeling the past once we know what happened? I backtested them and they seemed very accurate.

**Comment by tr8dr** [comment]
This is not an online indicator, I suppose I should clarify that in the documentation.  It does determine the labels looking forward.   Its use it primarily in identifying moves ex-post or for purposes of labeling for ML.

Running tick to tick the labeler would have a lag of Tinactive or minimum amplitude before transitioning label state.   I do, however, use this labeler in live trading, not to directly predict current move, but to look backward identifying past moves.   Recent past moves can be useful in predicting forward behavior.

**Comment by jkravets1** [comment]
Thanks, that make sense.

**Comment by flamby** [comment]
So if i understood correctly, it has lookahead bias. 
if so, do you plan to implement one w/o lookahead bias to make it useful as a feature for ML prediction, like you do, in a sense, when using it in live trading?
Or perhaps, what I'm suggesting does not make sense at all.

**Comment by tr8dr** [comment]
The labeler obtains its accuracy by evaluating with a forward view.  It is not intended to be an online indicator.    There is no online indicator that will be able to accurately label without lag short of knowing or being able to predict the future.   If there was someone with a model that could predict the future accurately, then the market would be quite different, with all opportunities arbitraged out.

In terms of lag, you could, for example use a spline or MA construct to determine a smoothed view of prices and label accordingly.  However any form of smoothing introduces lag in proportion to the degree of smoothing.

**Comment by flamby** [comment]
thanks for the clarification
