### ISSUE TITLE
HMMExponential2State needs ExponentialDistribution

### ISSUE THREAD

**Issue by jkravets1** [tr8dr/tseries-patterns#4]
Great post on the hidden markov models on your blog!
 I was trying to use  HMMExponential2State(HMM) but I think the exponential distribution function is missing. Would you mind uploading this function?

from research.math.distributions import ExponentialDistribution

Thanks for the blog overall, best open source stuff I found in years!

**Comment by jkravets1** [comment]
Nevermind I fixed my issue.

**Comment by tr8dr** [comment]
Thanks for pointing out.  I should adjust the source.  As you can see, i pulled this out from my proprietary source base.  Forgot to transfer this over.

**Comment by tr8dr** [comment]
I added the missing distribution classes.  Thanks
